In [ ]:
import torch
import numpy as np

a = torch.FloatTensor(3, 2)
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
torch.FloatTensor([[1, 2, 3], [5, 7, 8]])

tensor([[1., 2., 3.],
        [5., 7., 8.]])

In [ ]:
n = np.zeros(shape=(3, 2))
n

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
b = torch.tensor(n)

In [5]:
b

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

In [ ]:
n = np.zeros(shape=(3, 2), dtype=np.float32)
c = torch.tensor(n)
c

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [ ]:
n = np.zeros(shape=(3, 2))
torch.tensor(n, dtype=torch.float64)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

### Scaler Tensors 

In [ ]:
a = torch.tensor([1, 2, 4])
a

tensor([1, 2, 4])

In [ ]:
s = a.sum()
s

tensor(7)

In [11]:
s.item()

7

In [12]:
torch.tensor(1)

tensor(1)

In [ ]:
a = torch.tensor([1, 3])
a

tensor([1, 3])

In [ ]:
ca = a.to("mps")
ca

tensor([1, 3], device='mps:0')

In [ ]:
device = "mps" if torch.mps.is_available() else "cpu"
device

'mps'

In [ ]:
a + 1

tensor([2, 4])

In [ ]:
ca + 1

tensor([2, 4], device='mps:0')

In [19]:
ca.device

device(type='mps', index=0)

### Tensor and Gradient 

In [ ]:
v1 = torch.tensor([1.0, 1.0], requires_grad=True)
v2 = torch.tensor([2.0, 2.0])
print(v1, v2)

tensor([1., 1.], requires_grad=True) tensor([2., 2.])


In [ ]:
v_sum = v1 + v2
print(v_sum)
v_res = (v_sum * 2).sum()
v_res

tensor([3., 3.], grad_fn=<AddBackward0>)


tensor(12., grad_fn=<SumBackward0>)

In [ ]:
v1.is_leaf, v2.is_leaf

(True, True)

In [ ]:
v_sum.is_leaf, v_res.is_leaf

(False, False)

In [ ]:
v1.requires_grad, v2.requires_grad

(True, False)

In [ ]:
v_sum.requires_grad, v_res.requires_grad

(True, True)

In [ ]:
cc = v_res.backward()
print(cc)
v1.grad

None


tensor([2., 2.])

In [27]:
v2.grad

### NN Building Blocks


In [ ]:
import torch.nn as nn

l = nn.Linear(2, 5)
v = torch.FloatTensor([2, 4])
l(v)

tensor([-0.2946,  0.7199,  2.0451,  1.0042, -2.4985], grad_fn=<ViewBackward0>)

In [ ]:
s = nn.Sequential(
    nn.Linear(2, 5),
    nn.ReLU(),
    nn.Linear(5, 20),
    nn.ReLU(),
    nn.Linear(20, 10),
    nn.Dropout(p=0.3),
    nn.Softmax(dim=1),
)
s

Sequential(
  (0): Linear(in_features=2, out_features=5, bias=True)
  (1): ReLU()
  (2): Linear(in_features=5, out_features=20, bias=True)
  (3): ReLU()
  (4): Linear(in_features=20, out_features=10, bias=True)
  (5): Dropout(p=0.3, inplace=False)
  (6): Softmax(dim=1)
)

In [ ]:
s(torch.FloatTensor([[1, 2]]))

tensor([[0.0886, 0.0886, 0.1009, 0.0886, 0.1314, 0.1176, 0.1181, 0.0886, 0.0886,
         0.0886]], grad_fn=<SoftmaxBackward0>)

Custom Layers

In [ ]:
from ast import Num


class OurModule(nn.Module):
    def __init__(self, num_inputs, num_classes, dropout_prob=0.3):
        super(OurModule, self).__init__()
        self.pipe = nn.Sequential(
            nn.Linear(num_inputs, 5),
            nn.ReLU(),
            nn.Linear(5, 20),
            nn.ReLU(),
            nn.Linear(20, num_classes),
            nn.Dropout(p=dropout_prob),
            nn.Softmax(dim=1),
        )

    def forward(self, x):
        return self.pipe(x)

In [ ]:
net = OurModule(num_inputs=2, num_classes=3)
v = torch.FloatTensor([[2, 3]])
out = net(v)
print(net)
print(out)

OurModule(
  (pipe): Sequential(
    (0): Linear(in_features=2, out_features=5, bias=True)
    (1): ReLU()
    (2): Linear(in_features=5, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=3, bias=True)
    (5): Dropout(p=0.3, inplace=False)
    (6): Softmax(dim=1)
  )
)
tensor([[0.2654, 0.4241, 0.3105]], grad_fn=<SoftmaxBackward0>)


### TensorBoard

In [45]:
!pip install tensorboardX


In [47]:
import math 
from tensorboardX import SummaryWriter

writer = SummaryWriter()
funcs={"sin":math.sin,"cos":math.cos,"tan":math.tan}

for angle in range(-360,360):
    angle_rad = angle*math.pi/180
    for name,fun in funcs.items():
        val = fun(angle_rad)
        writer.add_scalar(name,val,angle)
writer.close()